stages:
  - build
  - deploy

variables:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: "AngularGitLab"

build:
  stage: build
  image: node:14
  script:
    - npm ci
    - npm run build -- --prod

deploy:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install awscli
  script:
    - aws s3 sync dist s3://$S3_BUCKET_NAME --delete
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET_NAME --s3-key $S3_KEY
