stages:
  - build
  - archive
  - deploy

variables:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: "AngularGitLab"

build:
  stage: build
  image: node:14
  script:
    - npm ci
    - npm run build -- --prod

archive:
  stage: archive
  before_script:
    - apt-get update
    - apt-get install zip -y
  script:
    - echo "Archiving lambda code"
    - zip -r $CI_PROJECT_NAME.zip *

  artifacts:
    paths:
      - $CI_PROJECT_NAME.zip

deploy:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install awscli
    - aws --version
  script:
    - echo "Deploying code"
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$CI_PROJECT_NAME.zip
